"""create audit events

Revision ID: 0e82b0c4b72e
Revises: f5d7b247b2e2
Create Date: 2026-09-29 03:28:20.777032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e82b0c4b72e'
down_revision: Union[str, Sequence[str], None] = 'f5d7b247b2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('permission_key', sa.String(length=200), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=200), nullable=True),
    sa.Column('correlation_id', sa.String(length=200), nullable=True),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_decision_occurred_at', 'audit_events', ['decision', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_event_type_occurred_at', 'audit_events', ['event_type', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_organization_occurred_at', 'audit_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_user_occurred_at', 'audit_events', ['user_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_user_occurred_at', table_name='audit_events')
    op.drop_index('ix_audit_events_organization_occurred_at', table_name='audit_events')
    op.drop_index('ix_audit_events_event_type_occurred_at', table_name='audit_events')
    op.drop_index('ix_audit_events_decision_occurred_at', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
