"""create leads

Revision ID: 731120dd702c
Revises: 2e091d57dc86
Create Date: 2026-09-29 20:31:06.653281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731120dd702c'
down_revision: Union[str, Sequence[str], None] = '2e091d57dc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('interest', sa.String(length=30), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('next_action', sa.String(length=500), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id', 'organization_id'], ['contacts.id', 'contacts.organization_id'], name='fk_leads_contact_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id', 'organization_id'], ['organization_memberships.user_id', 'organization_memberships.organization_id'], name='fk_leads_owner_membership_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_interest'), 'leads', ['interest'], unique=False)
    op.create_index(op.f('ix_leads_is_active'), 'leads', ['is_active'], unique=False)
    op.create_index(op.f('ix_leads_next_action_at'), 'leads', ['next_action_at'], unique=False)
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_leads_outcome'), 'leads', ['outcome'], unique=False)
    op.create_index(op.f('ix_leads_owner_user_id'), 'leads', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_owner_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_outcome'), table_name='leads')
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_next_action_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_is_active'), table_name='leads')
    op.drop_index(op.f('ix_leads_interest'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
