"""create import batches

Revision ID: 96348ac0352e
Revises: d66f07ec1ef7
Create Date: 2026-10-10 10:52:26.488248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96348ac0352e'
down_revision: Union[str, Sequence[str], None] = 'd66f07ec1ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_format', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('successful_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'validating', 'processing', 'completed', 'completed_with_errors', 'failed', 'cancelled')", name='ck_import_batches_status'),
    sa.CheckConstraint('failed_rows >= 0', name='ck_import_batches_failed_rows_nonnegative'),
    sa.CheckConstraint('file_size_bytes IS NULL OR file_size_bytes >= 0', name='ck_import_batches_file_size_nonnegative'),
    sa.CheckConstraint('processed_rows >= 0', name='ck_import_batches_processed_rows_nonnegative'),
    sa.CheckConstraint('skipped_rows >= 0', name='ck_import_batches_skipped_rows_nonnegative'),
    sa.CheckConstraint('successful_rows >= 0', name='ck_import_batches_successful_rows_nonnegative'),
    sa.CheckConstraint('total_rows >= 0', name='ck_import_batches_total_rows_nonnegative'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_organization_id'), 'import_batches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_organization_id'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
